name: CI/CD

on:
  push:
    branches: [master]
  schedule:
    - cron: "20 16 */7 * *"
  release:
    types: [created]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ["**"]

# Only run once due to API rate limits
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ## ===========================================================================
  ##    Builds the tool on multiple OS
  ##
  Build:
    uses: ./.github/workflows/_build.yaml
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
    with:
      os: ${{ matrix.os }}
